version: "3.2"
services:
  velik_oli:
    container_name: velik_oli
    image: ruby:3-alpine
    working_dir: /usr/src/app/velik
    command: sh -c "apk add build-base && bundle install && bundle exec ruby main.rb nakilon Oli_Dormant"
    volumes:

      - type: bind
        source: ./main.rb
        target: /usr/src/app/velik/main.rb
        read_only: true
      - type: bind
        source: ../trovobot.rb
        target: /usr/src/app/trovobot.rb
        read_only: true
      - type: bind
        source: ../common.rb
        target: /usr/src/app/common.rb
        read_only: true
      - type: bind
        source: ./Gemfile
        target: /usr/src/app/velik/Gemfile
        read_only: true
      - type: bind
        source: ./Gemfile.lock
        target: /usr/src/app/velik/Gemfile.lock
        read_only: true

      - type: bind
        source: ./tokens.json
        target: /usr/src/app/velik/tokens.json
      - type: bind
        source: ./clientid
        target: /usr/src/app/velik/clientid
        read_only: true
      - type: bind
        source: ./clientsecret
        target: /usr/src/app/velik/clientsecret
        read_only: true

      - type: bind
        source: ./processed.jsonl
        target: /usr/src/app/velik/processed.jsonl
      - type: bind
        source: ./db.yaml
        target: /usr/src/app/velik/db.yaml
